export default {
  GET_MOVIES_REQUEST: "GET_MOVIES_REQUEST",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_MOVIES_FAILED: "GET_MOVIES_FAILED",
  GET_GENRE_REQUEST: "GET_GENRE_REQUEST",
  GET_GENRE_SUCCESS: "GET_GENRE_SUCCESS",
  GET_GENRE_FAILED: "GET_GENRE_FAILED",

  GET_DETAIL_REQUEST: "GET_DETAIL_REQUEST",
  GET_DETAIL_SUCCESS: "GET_DETAIL_SUCCESS",
  GET_DETAIL_FAILED: "GET_DETAIL_FAILED",

};
